2021-12-30 11:48:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:48:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:49:02 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/home/views.py changed, reloading.
2021-12-30 11:49:02 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/home/views.py changed, reloading.
2021-12-30 11:49:05 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:49:05 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:53:01 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:53:01 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:55:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:55:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:55:59 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:55:59 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 11:56:10 [ INFO    ] (basehttp.log_message) "GET /news HTTP/1.1" 301 0
2021-12-30 11:56:10 [ INFO    ] (basehttp.log_message) "GET /news HTTP/1.1" 301 0
2021-12-30 11:56:11 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 13232
2021-12-30 11:56:11 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 13232
2021-12-30 11:56:15 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:15 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:15 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:15 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:16 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:16 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:16 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:16 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:17 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:17 [ WARNING ] (log.log_response) Not Found: /news/get-data/
2021-12-30 11:56:17 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:17 [ WARNING ] (basehttp.log_message) "GET /news/get-data/ HTTP/1.1" 404 3824
2021-12-30 11:56:35 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:56:35 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:56:35 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66179
2021-12-30 11:56:35 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66179
2021-12-30 11:57:31 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:31 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:31 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:31 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:32 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:32 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:32 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:32 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:34 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:34 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:34 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:34 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:35 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:35 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:35 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:35 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66316
2021-12-30 11:57:38 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 13232
2021-12-30 11:57:38 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 13232
2021-12-30 11:57:42 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:42 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:57:42 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66179
2021-12-30 11:57:42 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66179
2021-12-30 11:59:11 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:11 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:11 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66188
2021-12-30 11:59:11 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66188
2021-12-30 11:59:14 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:14 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:14 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66325
2021-12-30 11:59:14 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66325
2021-12-30 11:59:20 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 13232
2021-12-30 11:59:20 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 13232
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/css/form.css HTTP/1.1" 200 360
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/css/form.css HTTP/1.1" 200 360
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/css/index.css HTTP/1.1" 200 1054
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/css/index.css HTTP/1.1" 200 1054
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/icovid.svg HTTP/1.1" 200 4289
2021-12-30 11:59:24 [ INFO    ] (basehttp.log_message) "GET /static/icovid.svg HTTP/1.1" 200 4289
2021-12-30 11:59:25 [ INFO    ] (basehttp.log_message) "GET /static/background.jpg HTTP/1.1" 200 376611
2021-12-30 11:59:25 [ INFO    ] (basehttp.log_message) "GET /static/background.jpg HTTP/1.1" 200 376611
2021-12-30 11:59:31 [ WARNING ] (log.log_response) Bad Request: /auth/api/login/
2021-12-30 11:59:31 [ WARNING ] (log.log_response) Bad Request: /auth/api/login/
2021-12-30 11:59:31 [ WARNING ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 400 57
2021-12-30 11:59:31 [ WARNING ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 400 57
2021-12-30 11:59:37 [ WARNING ] (log.log_response) Bad Request: /auth/api/login/
2021-12-30 11:59:37 [ WARNING ] (log.log_response) Bad Request: /auth/api/login/
2021-12-30 11:59:37 [ WARNING ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 400 57
2021-12-30 11:59:37 [ WARNING ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 400 57
2021-12-30 11:59:42 [ INFO    ] (basehttp.log_message) "GET /auth/loginsso/ HTTP/1.1" 302 0
2021-12-30 11:59:42 [ INFO    ] (basehttp.log_message) "GET /auth/loginsso/ HTTP/1.1" 302 0
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /auth/loginsso/?next=%2Fauth%2Flogin%2F&ticket=ST-79-mabJdTSQcng2uEo1lFvU-sso.ui.ac.id HTTP/1.1" 302 0
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /auth/loginsso/?next=%2Fauth%2Flogin%2F&ticket=ST-79-mabJdTSQcng2uEo1lFvU-sso.ui.ac.id HTTP/1.1" 302 0
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 302 0
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 302 0
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20058
2021-12-30 11:59:52 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20058
2021-12-30 11:59:53 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 302 0
2021-12-30 11:59:53 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 302 0
2021-12-30 11:59:53 [ INFO    ] (basehttp.log_message) "GET /accounts/login/?next=/administrator/get-announcement HTTP/1.1" 200 47
2021-12-30 11:59:53 [ INFO    ] (basehttp.log_message) "GET /accounts/login/?next=/administrator/get-announcement HTTP/1.1" 200 47
2021-12-30 11:59:58 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:58 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 11:59:58 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66857
2021-12-30 11:59:58 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66857
2021-12-30 12:00:00 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:00 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:00 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:00 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:01 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:01 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:01 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:01 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:02 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:02 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:02 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:02 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:04 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:04 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:00:04 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:04 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66994
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20058
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20058
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 302 0
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 302 0
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /accounts/login/?next=/administrator/get-announcement HTTP/1.1" 200 47
2021-12-30 12:00:13 [ INFO    ] (basehttp.log_message) "GET /accounts/login/?next=/administrator/get-announcement HTTP/1.1" 200 47
2021-12-30 12:00:48 [ INFO    ] (basehttp.log_message) "GET /auth/logout/ HTTP/1.1" 302 0
2021-12-30 12:00:48 [ INFO    ] (basehttp.log_message) "GET /auth/logout/ HTTP/1.1" 302 0
2021-12-30 12:00:48 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 12:00:48 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 12:01:10 [ INFO    ] (basehttp.log_message) "GET /auth/signup/ HTTP/1.1" 200 5835
2021-12-30 12:01:10 [ INFO    ] (basehttp.log_message) "GET /auth/signup/ HTTP/1.1" 200 5835
2021-12-30 12:02:01 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:02:01 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:02:03 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 12:02:03 [ INFO    ] (basehttp.log_message) "GET /auth/login/ HTTP/1.1" 200 4024
2021-12-30 12:02:08 [ INFO    ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 200 28
2021-12-30 12:02:08 [ INFO    ] (basehttp.log_message) "POST /auth/api/login/ HTTP/1.1" 200 28
2021-12-30 12:02:08 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20334
2021-12-30 12:02:08 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 20334
2021-12-30 12:02:09 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:09 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:17 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:17 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:17 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:17 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:19 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:19 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:19 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:19 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /forum HTTP/1.1" 301 0
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /forum HTTP/1.1" 301 0
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /forum/ HTTP/1.1" 200 5563
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /forum/ HTTP/1.1" 200 5563
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /static/css/style.css HTTP/1.1" 200 206896
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /static/css/style.css HTTP/1.1" 200 206896
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:23 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:23 [ WARNING ] (log.log_response) Not Found: /forum/assets/favicon.ico
2021-12-30 12:02:23 [ WARNING ] (log.log_response) Not Found: /forum/assets/favicon.ico
2021-12-30 12:02:23 [ WARNING ] (basehttp.log_message) "GET /forum/assets/favicon.ico HTTP/1.1" 404 3870
2021-12-30 12:02:23 [ WARNING ] (basehttp.log_message) "GET /forum/assets/favicon.ico HTTP/1.1" 404 3870
2021-12-30 12:02:24 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:24 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 20334
2021-12-30 12:02:25 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:25 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:02:32 [ INFO    ] (basehttp.log_message) "GET /admin HTTP/1.1" 301 0
2021-12-30 12:02:32 [ INFO    ] (basehttp.log_message) "GET /admin HTTP/1.1" 301 0
2021-12-30 12:02:32 [ INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 10222
2021-12-30 12:02:32 [ INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 10222
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/base.css HTTP/1.1" 200 19513
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/base.css HTTP/1.1" 200 19513
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
2021-12-30 12:02:33 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 9680
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 9680
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/core.js HTTP/1.1" 200 5698
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/core.js HTTP/1.1" 200 5698
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2021-12-30 12:02:36 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
2021-12-30 12:02:38 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11049
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11049
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:04 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:07 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:03:07 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:03:07 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:07 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11267
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11267
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:22 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:26 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 9687
2021-12-30 12:03:26 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 9687
2021-12-30 12:03:26 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:26 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:28 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/add/ HTTP/1.1" 200 12705
2021-12-30 12:03:28 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/add/ HTTP/1.1" 200 12705
2021-12-30 12:03:28 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:28 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "POST /admin/home/feedback/add/ HTTP/1.1" 302 0
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "POST /admin/home/feedback/add/ HTTP/1.1" 302 0
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11027
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11027
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:43 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:46 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/add/ HTTP/1.1" 200 12705
2021-12-30 12:03:46 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/add/ HTTP/1.1" 200 12705
2021-12-30 12:03:46 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:46 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "POST /admin/home/feedback/add/ HTTP/1.1" 302 0
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "POST /admin/home/feedback/add/ HTTP/1.1" 302 0
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11229
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11229
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:03:57 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:04:04 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:04 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:04 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66392
2021-12-30 12:04:04 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66392
2021-12-30 12:04:05 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:05 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:05 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66529
2021-12-30 12:04:05 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66529
2021-12-30 12:04:06 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:06 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-data
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:06 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66529
2021-12-30 12:04:06 [ ERROR   ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 500 66529
2021-12-30 12:04:09 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 25362
2021-12-30 12:04:09 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 25362
2021-12-30 12:04:09 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 200 161850
2021-12-30 12:04:09 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 200 161850
2021-12-30 12:04:10 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 200 174122
2021-12-30 12:04:10 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 200 174122
2021-12-30 12:04:10 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:04:10 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:04:12 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:12 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:12 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66401
2021-12-30 12:04:12 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66401
2021-12-30 12:04:30 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:30 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:30 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66538
2021-12-30 12:04:30 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66538
2021-12-30 12:04:31 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:31 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:04:31 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66538
2021-12-30 12:04:31 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66538
2021-12-30 12:06:17 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:06:17 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 25362
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 25362
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:06:23 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:06:24 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:24 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:32 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:32 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:33 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:33 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:36 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:36 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:37 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:37 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:38 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:38 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:38 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:38 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:43 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:44 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:44 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:44 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:44 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:45 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:45 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:06:45 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:06:45 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min.jpg HTTP/1.1" 304 0
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:07:08 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:07:09 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:09 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /tracker HTTP/1.1" 301 0
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /tracker HTTP/1.1" 301 0
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /tracker/ HTTP/1.1" 200 11402
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /tracker/ HTTP/1.1" 200 11402
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /static/script.js HTTP/1.1" 200 7286
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /static/script.js HTTP/1.1" 200 7286
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:10 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:12 [ INFO    ] (basehttp.log_message) "GET /forum/ HTTP/1.1" 200 5563
2021-12-30 12:07:12 [ INFO    ] (basehttp.log_message) "GET /forum/ HTTP/1.1" 200 5563
2021-12-30 12:07:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:16 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:16 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:17 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:17 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:18 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:19 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:19 [ INFO    ] (basehttp.log_message) "GET /news/ HTTP/1.1" 200 25362
2021-12-30 12:07:20 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:20 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:07:31 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:07:31 [ ERROR   ] (log.log_response) Internal Server Error: /home/get-data/
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view home.views.get_data didn't return an HttpResponse object. It returned None instead.
2021-12-30 12:07:31 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66401
2021-12-30 12:07:31 [ ERROR   ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 500 66401
2021-12-30 12:08:57 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/home/views.py changed, reloading.
2021-12-30 12:08:57 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/home/views.py changed, reloading.
2021-12-30 12:09:03 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:09:03 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:09:06 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:09:06 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:09:22 [ INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 11260
2021-12-30 12:09:22 [ INFO    ] (basehttp.log_message) "GET /admin/ HTTP/1.1" 200 11260
2021-12-30 12:09:27 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11034
2021-12-30 12:09:27 [ INFO    ] (basehttp.log_message) "GET /admin/home/feedback/ HTTP/1.1" 200 11034
2021-12-30 12:09:27 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:27 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:31 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11057
2021-12-30 12:09:31 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11057
2021-12-30 12:09:31 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:31 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:33 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:09:33 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:09:33 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:33 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11484
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11484
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:49 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:51 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:09:51 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/add/ HTTP/1.1" 200 12479
2021-12-30 12:09:52 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:52 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:09:57 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
2021-12-30 12:09:57 [ INFO    ] (basehttp.log_message) "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "POST /admin/news/article/add/ HTTP/1.1" 302 0
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11701
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "GET /admin/news/article/ HTTP/1.1" 200 11701
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:10:13 [ INFO    ] (basehttp.log_message) "GET /admin/jsi18n/ HTTP/1.1" 200 3195
2021-12-30 12:10:18 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 26765
2021-12-30 12:10:18 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 26765
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_dGySF0f.jpg HTTP/1.1" 200 161850
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_dGySF0f.jpg HTTP/1.1" 200 161850
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_vIF5Dpy.jpg HTTP/1.1" 200 161850
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_vIF5Dpy.jpg HTTP/1.1" 200 161850
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:10:19 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:10:30 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:30 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:40 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:40 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:41 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:41 [ INFO    ] (basehttp.log_message) "GET /news/get-data HTTP/1.1" 200 149
2021-12-30 12:10:44 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:10:44 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:11:11 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:11:11 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:11:15 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:11:15 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:12:05 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:12:05 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:12:10 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:12:10 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:12:35 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:12:35 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/urls.py changed, reloading.
2021-12-30 12:12:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:12:39 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:12:51 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:12:51 [ INFO    ] (basehttp.log_message) "GET /home/get-data/ HTTP/1.1" 200 149
2021-12-30 12:13:12 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 26765
2021-12-30 12:13:12 [ INFO    ] (basehttp.log_message) "GET /home/ HTTP/1.1" 200 26765
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_vIF5Dpy.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_vIF5Dpy.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/ciella.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_dGySF0f.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /media/EUREKA_LOGO-min_dGySF0f.jpg HTTP/1.1" 304 0
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:13:13 [ INFO    ] (basehttp.log_message) "GET /administrator/get-announcement HTTP/1.1" 200 2
2021-12-30 12:13:24 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-article
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/views.py", line 93, in get_article
    data = json.dumps(articles_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
2021-12-30 12:13:24 [ ERROR   ] (log.log_response) Internal Server Error: /news/get-article
Traceback (most recent call last):
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/views.py", line 93, in get_article
    data = json.dumps(articles_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
2021-12-30 12:13:25 [ ERROR   ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 500 91216
2021-12-30 12:13:25 [ ERROR   ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 500 91216
2021-12-30 12:13:46 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/views.py changed, reloading.
2021-12-30 12:13:46 [ INFO    ] (autoreload.trigger_reload) /Users/graciella/Documents/FASILKOM SEM 3/PBP/icovid/news/views.py changed, reloading.
2021-12-30 12:13:50 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:13:50 [ INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2021-12-30 12:13:51 [ INFO    ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 200 396
2021-12-30 12:13:51 [ INFO    ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 200 396
2021-12-30 12:13:59 [ INFO    ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 200 396
2021-12-30 12:13:59 [ INFO    ] (basehttp.log_message) "GET /news/get-article HTTP/1.1" 200 396
